### PR TITLE
Add seeded choice in bracket lists

### PR DESCRIPTION
**Pull request by satche**
Well, since you quickly add my PR, I have another one to suggest :D

Let say I have a the following prompt:
```
<color> car, <color> house

>>>color
[red|blue|green|yellow]
```

It will output something like `red car, blue house`. What if I want to match <color> everytime ? It's now possible with `!` pattern

```
<color> car, <color> house

>>>color
[!red|blue|green|yellow]
```

Output: `red car, red house`, `blue car, blue house`, etc

And it stills works with other patterns: `[!1-2#10:red|blue|green|yellow]` will always output the same 1 or 2 colors, that are less likely to be red.

### CODE REVIEW

**Comment by satche** [comment]
Well I just realized there is a bug. I think that if you use `[!foo|bar]` one time, it will then keep a seed for the rest of the variables. Working on it

**Comment by satche** [comment]
Ok, should work now. Some things to note
```
>>>color
[red|blue|green]

>>>seed_color
[!red|blue|green]
```

`[!<color>]` won't use a seed, that's why we have to duplicate it into `seed_color`

`[80:<foo>|<bar>]` won't use a seed for the weighted choice, even if `<foo>` and `<bar>` are seeded
`[!80:<foo>|<bar>]` will use the seed to do the weighted choice

**Comment by tudal** [comment]
I'm not sure about this one. Seems problematic in code and usage (potential problems hard to detect since its random).

I'm planning to add also random numbers generation and would be nice to have something universal to remember random values, like to store them in variables:

```
I drive V#CAR[red|blue|green] carV#CAR and my sister also drive V#CAR
```
So after you generate prompt
```
I drive V#CARred carV#CAR and my sister also drive V#CAR
```
There's one more pass for variable sets + remove syntax. And replace/apply to rest
```
I drive red car and my sister also drive red car
```

Really no idea about syntax for this one.

**Comment by satche** [comment]
I understand. Maybe as an experimental feature ? As you want! I'll play with it a bit on my side.
But named variables sounds great! Syntax as you suggested seem a bit confusing. I don't know if `{}` brackets could be used ? Something like this:
```
I drive $car={[red|blue|green] car} and my sister also drive $car
```

**Comment by satche** [comment]
So, just to let you know of some other changes I made here.

Regular bracket-list syntax works as usual. I just added the seed to the choice, so it's the same result across multiple generations
Screenshot 2024-06-23 at 18 23 48

`[!…]` is the "freeze" syntax: even if called multiple time, it will always keep the same value
Screenshot 2024-06-23 at 18 24 19

If we really want something randomized everytime, we have the `[?…]` syntax, which will take an external randomized seed. Values will be randomized even across multiple generations
Screenshot 2024-06-23 at 18 24 29

It's just to let you know of the change, feel free to integrate it or not :)
I will play a bit with it to see how it works out

**Comment by satche** [comment]
Yeah, scratch that. I tested and it's too clunky.
Variables as you suggested are definitely a better solution if we want to have control over what's generated and what's not.

**Pull request closed without merging**
